@extends('layout.header')
@section('content')
@endsection
<section id="inner_about" class="inner_bg_white">
			<div class="inner_section clearfix">
				<h1>Message from the Chief Patronizer</h1>
				<p><img width="315" height="232" src="../minister.png" alt="Principal"/></p>
				<p>Schooling is undergoing a fundamental transformation, the world over.<br />As a parent, you are very likely to be interested in a progressive education for your ward.This is  good news because it means we share a vision about what education means to our children and  also to the Educational development and the future of our UAE.<strong><span><span><span><br /></span></span></span><span><br /></span><span><span><span>To quote Dr. APJ Abdul Kalam</span></span></span><span><span><span> <br />“Teaching is a very noble profession that shapes the character, caliber, and future of an individual. If the people remember me as a good teacher that will be the biggest honour for me”</span></span></span></strong></p>
				<p><strong><span><span>– Dr. APJ Abdul Kalam</span></span><span><br /><br /></span></strong>Our vision is to Educate, Enlighten and Empowerthe students as we believe that each child comes into the world with a personal destiny to fulfill, equipped with all of the aptitudes and talents required to realize his or her ultimate purpose.<br />As educators, it is our duty to create an environment that nurtures and cultivates each person's gift, providing experiences through which they develop and hone essential skills including, most essentially of all, how to gain the knowledge they need and to apply that knowledge in creative new ways to make a unique contribution to their world.  <br />It is an honour and a privilege to be the Principal of Sharjah Indian School.Sharjah Indian School stands for excellence and continuously sets higher standards by raising the bar.<br />At SIS, we are not only committed to maintain the impeccable image and highest standards, but also to carry it forward to newer heights.We firmly believe it can be achieved by experiential learning, techno savvy methodologies, effective assessment and providing academic ownership to the students, by focusing on creative and critical thinking.<br />The importance of education in the life of an individual cannot be overstated. It shapes individuals in their formative years and imbues in them values that would govern all their choices in life. </p>
				<p>It is said ‘If you are planning for a year, sow rice; if you are planning for a decade, plant trees; if you are planning for a lifetime, educate people’. Indeed, one can even say that the quality of education will determine the destiny of a nation.</p>
				<p><strong> In the words of Mr. Abraham Lincoln</strong><br /><strong>“You cannot escape the responsibility of tomorrow by evading it today.”</strong><strong>         </strong></p>
				<p><strong>– Abraham Lincoln</strong></p>
				<p><br />For us, education does not mean providing answers. It means equipping the pupil with the means to find the answers for himself / herself and within himself / herself. Education empowers students to discover themselves. Within each student is a doctor, an engineer, a teacher, a social activist, a sports person, an environmentalist, a poet, an author or an economist. </p>
				<p>The teachers support them in channelizing resources vis-à-vis their dreams thus, sustainably generating civilized and productive human capital for serving the community in line with our values of “Service before Self”.<br />It is, therefore extremely important for schools today to define themselves in the market place. What does our school stand for? What is that the parents can expect from the school? <br />We at Sharjah Indian School are very clear about what we want to deliver. We strive to produce young minds who wish to engage with the world of knowledge, minds that are hungry for “more”. It is our considered belief that if the process is right, the results will follow.<br />Over the years in various schools, we have witnessed in our students an unparalleled knowledge base, a vibrant dynamism, an acute consciousness about the world around them, a focused ambition and a sustained commitment.<br />We are also fortunate to have an experienced and committed team. <br />I, along with my team of silent workers and dedicated faculty, intend to build on this strong foundation and raise the standards in all spheres, to the zenith. <br />And most of  all, we are committed to producing GLOBAL citizens with a secular world view, citizens who respect and celebrate differences, and see differences as a unique opportunity to mould a strong nation. </p>
				<p><strong>To quote M.K. Gandhi</strong><br /><strong>“Happiness is when what you think, what you say, and what you do are in harmony.”</strong></p>
				<p><strong>– M.K. Gandhi</strong></p>
				<p>We want to ensure smile on the faces of each student by our stress-free approach of teaching – learning and assessment process, to contribute and enhance the overall happiness index of this great nation.<br />I personally assure you that my doors will always be open to the students and their parents for any suggestion or guidance. We invite you to be partners in our development processes.<br /> </p>
				<p><strong>Advocate Mostafizur Rahman</strong><br /><strong>Minister of primary and mass education ,</strong><br/><strong>Cheif Patronizer,</strong><br /><strong>Bir Muktijoddha Mostafizur Rahman Institute</strong></p>
			</div>
		</section>
@extends('layout.footer')
@section('content')
@endsection
